### PR TITLE
Re-factor Bot and Behaviours

### PR DESCRIPTION
**Pull request by Boarders**
- Change Bot to use monad transformer representation giving a
    monadic  interface

  - Use new interface to re-write behaviours to be less tied to
    particular representation

### CODE REVIEW

**Comment by solomon-b** [comment]
This is really cool. Can we have a `MonadTrans` instance for `Bot` with this?

**Comment by Boarders** [comment]
I wanted to add that, my issue was that the class is defined as:
```haskell
class MonadTrans t where
```
Here the kind of `t` is `(Type -> Type) -> Type -> Type` and so we have a monad parameter in the wrong place in `Bot m s i o` but maybe someone knows a way around that kind of issue?

**Comment by solomon-b** [comment]
Oh bummer. Thats the same issue as for `Invariant`. Maybe we can use a type family fix it?

**Comment by solomon-b** [comment]
Are we waiting on anything before merging this?

**Review by solomon-b — APPROVED** [review]
I just familiarized myself with this PR and I think its good to merge as is. I like that we have examples of a monad style and a lambda style for setting basic bots.

**Pull request merged**
